fix: update export paths
Update paths to remove file extensions and use index for default
file in directories.

Fixes the following TypeScript error:

```
Cannot find module '@libp2p/http-fetch/auth.js' or its corresponding type declarations.
  There are types at '/Users/path/to/node_modules/@libp2p/http-fetch/dist/src/auth/auth.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
```

We can't update the module resolution yet due to compatibility issues
with other dependencies, namely that not all of them have `"types"`
fields in their exports maps yet.